[package]
name = "rrgrep"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.1", features = ["derive"] }
colored = "2.1.0"
glob = "0.3.1"
itertools = "0.12.1"
rayon = "1.8.1"
regex = "1.10.3"
thiserror = "1.0.57"
