[package]
name = "clap-examples"
version = "0.1.0"
edition = "2021"
authors = ["yjhtry"]
description = "clap examples description"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
